.github/workflows/build.yml

CI workflow that builds and pushes bootc‑based OCI images for each uBlue flavour.

Uses BuildKit entitlements exactly the way the upstream uBlue projects do.

name: Build bootc images

on: push: branches: [main] pull_request: branches: [main] workflow_dispatch:

-----------------------------------------------------------------------------

Global constants / secrets

-----------------------------------------------------------------------------

env: REGISTRY: ghcr.io IMAGE_REPO: huntergerlach/infra-upstream   # NOTE: must be lower‑case for GHCR

permissions: contents: read packages: write

jobs: bootc: runs-on: ubuntu-latest

strategy:
  fail-fast: false
  matrix:
    # ───── uBlue flavours you want to build ───────────────────────────────
    flavor: [bluefin, core, ucore]
    include:
      - flavor: bluefin
        fedora_tag: stable
      - flavor: core
        fedora_tag: stable
      - flavor: ucore
        fedora_tag: stable

steps:
  # ─────────────────── Pull source and set up build env ───────────────────
  - name: Checkout source
    uses: actions/checkout@v4

  - name: Set up QEMU (multi‑arch emulation)
    uses: docker/setup-qemu-action@v3

  - name: Set up Buildx with insecure entitlements
    id: buildx
    uses: docker/setup-buildx-action@v3
    with:
      install: true
      driver-opts: |
        network=host
        security.insecure=true

  - name: Log in to GHCR
    uses: docker/login-action@v3
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  # ───────────────────────── Build & push image ───────────────────────────
  - name: Build & push
    uses: docker/build-push-action@v5
    with:
      context: .
      file: Containerfile
      push: true
      provenance: false            # Skip SBOM/provenance for faster builds
      build-args: |
        FLAVOR=${{ matrix.flavor }}
        FEDORA_TAG=${{ matrix.fedora_tag }}
      # Tell BuildKit we really want the extra capabilities granted above
      allow: security.insecure,network.host

      # Image tags
      tags: |
        ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-latest
        ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-${{ github.sha }}

      # OCI labels
      labels: |
        org.opencontainers.image.title=${{ env.IMAGE_REPO }}
        org.opencontainers.image.version=${{ github.sha }}
        org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

