# .github/workflows/build-bluefin.yml
name: build-bluefin
on:
  push: { branches: [main] }
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME:     huntergerlach/infra-upstream

jobs:
  bluefin:
    runs-on: ubuntu-24.04     # buildah-build requires >=22.04
    permissions:
      contents: read
      packages: write
      id-token: write         # (for cosign, optional)

    steps:
      # 1️⃣  checkout
      - uses: actions/checkout@v4

      # 2️⃣  (optional) pull the base image first – helps on flaky networks
      - name: Pre-pull uBlue base
        run: |
          podman pull ghcr.io/ublue-os/bluefin:stable || true

      # 3️⃣  login to GHCR so the `podman push` inside buildah-build succeeds
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣  metadata labels (same as before)
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      # 5️⃣  **build** with Buildah
      - id: build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          context: .
          image: ${{ env.IMAGE_NAME }}
          tags: |
            bluefin-stable
            ${{ github.sha }}
          build-args: |
            FLAVOR=bluefin
            FEDORA_TAG=stable
          labels: ${{ steps.meta.outputs.labels }}
          # OCI false → produce docker-media-type, matches GHCR expectations
          oci: false
          # layers=true + a cache action gives you incremental speed-ups
          layers: true

      # 6️⃣  push                 (buildah-build *can* push automatically,
      #                             but retry wrappers are handy)
      - name: Push to GHCR
        uses: Wandalen/wretry.action@v3.8.0
        with:
          attempt_limit: 3
          attempt_delay: 15000
          action: redhat-actions/push-to-registry@v2
          with: |
            image: ${{ steps.build.outputs.image }}
            tags:  ${{ steps.build.outputs.tags }}
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            extra-args: |
              --disable-content-trust