name: Build-and-Publish bootc images

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FEDORA_VERSION: 40          # bump in one place when Fedora rolls
  # matrix list lives here for easy edits
  FLAVORS: core,bluefin

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flavor: ${{ fromJson('["' + env.FLAVORS.replace(',', '","') + '"]') }}

    steps:
    # ───────────── git clone ─────────────
    - name: Checkout source
      uses: actions/checkout@v4

    # ───────────── lower-case repo/owner for GHCR ─────────────
    - name: Normalise repo name (lowercase)
      run: |
        echo "IMAGE_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

    # ───────────── docker buildx setup ─────────────
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    # ───────────── GHCR login (built-in token) ─────────────
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ───────────── build & push ─────────────
    - name: Build and push ${{ matrix.flavor }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Containerfile
        build-args: |
          FLAVOR=${{ matrix.flavor }}
          FEDORA_VERSION=${{ env.FEDORA_VERSION }}
        provenance: false
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-${{ github.sha }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_REPO }}
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}