name: build-and-push

on:
  push: { branches: [main] }
  workflow_dispatch:
  schedule: [{ cron: '37 3 * * *' }]   # daily rebuild for security updates

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # desktop
          - { flavor: bluefin, fedora_tag: stable }
          # server
          - { flavor: ucore,   fedora_tag: stable }

    steps:
    # ── checkout ─────────────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ── lowercase owner/repo once, export as IMAGE_REPO ──────────────
    - name: Normalise repo name → lowercase
      shell: bash
      run: |
        image_repo="${GITHUB_REPOSITORY,,}"   # bash parameter-expansion
        echo "IMAGE_REPO=${image_repo}" >>"$GITHUB_ENV"

    # ── buildx toolchain ─────────────────────────────────────────────
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # ── login to GHCR (uses GITHUB_TOKEN) ────────────────────────────
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ── build + push ─────────────────────────────────────────────────
    - name: Build & push ${{ matrix.flavor }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Containerfile
        provenance: false
        push: true
        build-args: |
          FLAVOR=${{ matrix.flavor }}
          FEDORA_TAG=${{ matrix.fedora_tag }}
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-${{ github.sha }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_REPO }}
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}