name: build-bootc
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: huntergerlach/infra-upstream

jobs:
  build:
    runs-on: ubuntu-24.04            # Buildah officially supports 22.04+ / 24.04
    strategy:
      matrix:
        include:
          - BASE_FLAVOR: bluefin
            FEDORA_TAG:  stable
          # add more flavours / tags here

    steps:
      # ── checkout repo ────────────────────────────────────────────────────
      - uses: actions/checkout@v4

      # ── pull base image so we can retry on network hiccups (optional) ───
      - name: Pre-pull base
        run: |
          podman pull ghcr.io/ublue-os/${{ matrix.BASE_FLAVOR }}:${{ matrix.FEDORA_TAG }}

      # ── (optional) verify versions, set extra env, etc. ──────────────────
      # replicate whatever validation you need here (see ucore workflow)

      # ── build with Buildah (no entitlements needed) ─────────────────────
      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          context: .
          image: ${{ env.IMAGE_NAME }}
          tags: |
            ${{ matrix.BASE_FLAVOR }}-${{ matrix.FEDORA_TAG }}
            ${{ github.sha }}
          build-args: |
            FLAVOR=${{ matrix.BASE_FLAVOR }}
            FEDORA_TAG=${{ matrix.FEDORA_TAG }}
          labels: |
            org.opencontainers.image.version=${{ github.sha }}
          layers: true        # cache-friendly
          oci: false          # produce Docker-compat manifest

      # ── login & push to GHCR ─────────────────────────────────────────────
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags:  ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          extra-args: |
            --disable-content-trust   # optional; mirror of ucore action