# .github/workflows/build-bootc.yml
name: Build bootc images

on:
  # Build on every push to main; run manually if needed.
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Allow the job to push to GHCR
    permissions:
      contents: read
      packages: write

    # ─────── environment constants ──────────────────────────────────────────
    env:
      IMAGE_REGISTRY: ghcr.io
      IMAGE_NAME: huntergerlach/infra-upstream   # <org>/<repo>

    # ─────── build matrix ───────────────────────────────────────────────────
    # Add more flavours / tags here if you have them
    strategy:
      matrix:
        include:
          - BASE_FLAVOR: bluefin
            FEDORA_TAG: stable

    steps:
    # ─────────── checkout source ────────────────────────────────────────────
    - name: Checkout repository
      uses: actions/checkout@v4

    # ─────────── QEMU (for multi-arch; harmless if you stay on amd64) ──────
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # ─────────── BuildKit builder with insecure entitlements enabled ───────
    - name: Set up Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        driver-opts: network=host
        buildkitd-flags: |
          --allow-insecure-entitlement security.insecure
          --allow-insecure-entitlement network.host

    # ─────────── log in to GitHub Container Registry ────────────────────────
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ─────────── build & push the bootc/ostree image ────────────────────────
    - name: Build and push bootc image
      uses: docker/build-push-action@v5
      with:
        # Context & Dockerfile/Containerfile
        context: .
        file: Containerfile

        # Produce and push the image
        push: true
        provenance: false   # bootc images are reproducible; provenance optional

        # Allow privileged RPM-OStree operations inside the build container
        allow: |
          security.insecure
          network.host

        # Build-time arguments forwarded to the Containerfile
        build-args: |
          FLAVOR=${{ matrix.BASE_FLAVOR }}
          FEDORA_TAG=${{ matrix.FEDORA_TAG }}

        # Target tags
        tags: |
          ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.BASE_FLAVOR }}-${{ matrix.FEDORA_TAG }}
          ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

        # GitHub Actions cache for layer reuse
        cache-from: type=gha
        cache-to:   type=gha,mode=max