# .github/workflows/build-image.yml
name: Build & publish bootc image

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:        # optional: rebuild every night to pull in OS updates
    - cron: '11 2 * * *'

env:
  # ---- change these to taste --------------------------------------
  IMAGE_REGISTRY: ghcr.io                       # where to push
  IMAGE_NAME: ${{ github.repository }}          # e.g. huntergerlach/infra-upstream
  BASE_FLAVOR: bluefin                          # core | bluefin | ucore | …
  FEDORA_TAG: stable                            # stable | testing | rawhide …
  # -----------------------------------------------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:            # let the action push to GHCR
      contents:   read
      packages:   write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # ---------- BuildKit (Buildx) set-up -----------------------------------
      - name: Set up QEMU (multi-arch, harmless even if you build amd64 only)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx builder with insecure entitlements
        id: bk
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: |
            network=host
          buildkitd-flags: |
            --debug                         \
            --allow-insecure-entitlement security.insecure \
            --allow-insecure-entitlement network.host

      # ---------- Registry login --------------------------------------------
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------- Build & push ----------------------------------------------
      - name: Build and push bootc image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push:  true
          provenance: false
          # entitlements for rpm-ostree layer changes
          allow: security.insecure,network.host
          build-args: |
            FLAVOR=${{ env.BASE_FLAVOR }}
            FEDORA_TAG=${{ env.FEDORA_TAG }}
          # tags: human-readable + immutable digest tag
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BASE_FLAVOR }}-${{ env.FEDORA_TAG }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to:   type=gha,mode=max