name: Build-and-Publish bootc images

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io            # destination registry

jobs:
  build:
    runs-on: ubuntu-latest

    # Each row tells us which base tag exists on GHCR today.
    strategy:
      matrix:
        include:
          - flavor: core       # Server-style image
            tag:    latest     # ‘latest’ is public; 40/41/42 roll underneath
          - flavor: bluefin    # Desktop GNOME image
            tag:    latest     # numeric tags aren’t published; ‘latest’ is

    steps:
    # ─── checkout ────────────────────────────────────────────
    - uses: actions/checkout@v4

    # ─── lower-case owner/repo for GHCR naming ───────────────
    - name: Normalise repo name
      run: |
        echo "IMAGE_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >>"$GITHUB_ENV"

    # ─── buildx/QEMU toolchain ───────────────────────────────
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # ─── GHCR login (uses GITHUB_TOKEN) ──────────────────────
    - uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ─── build & push image ─────────────────────────────────
    - name: Build and push ${{ matrix.flavor }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Containerfile
        build-args: |
          FLAVOR=${{ matrix.flavor }}
          FEDORA_VERSION=${{ matrix.tag }}
        provenance: false
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-${{ github.sha }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_REPO }}
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}