# .github/workflows/build-bootc.yml
name: Build bootc images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      IMAGE_REGISTRY: ghcr.io
      IMAGE_NAME: huntergerlach/infra-upstream

    strategy:
      matrix:
        include:
          - BASE_FLAVOR: bluefin
            FEDORA_TAG: stable

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true
        driver-opts: network=host
        buildkitd-flags: |
          --allow-insecure-entitlement security.insecure
          --allow-insecure-entitlement network.host

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push bootc image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Containerfile
        push: true
        provenance: false

        # ───── THIS IS THE IMPORTANT PART ─────
        allow: |
          security.insecure
          network.host

        build-args: |
          FLAVOR=${{ matrix.BASE_FLAVOR }}
          FEDORA_TAG=${{ matrix.FEDORA_TAG }}

        tags: |
          ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.BASE_FLAVOR }}-${{ matrix.FEDORA_TAG }}
          ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

        cache-from: type=gha
        cache-to:   type=gha,mode=max