# .github/workflows/build-bootc.yml
name: Build bootc images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write   # provenance (disabled in build-push step)

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME:     huntergerlach/infra-upstream

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - BASE_FLAVOR: bluefin
            FEDORA_TAG:  stable

    steps:
      # ── Checkout ──────────────────────────────────────────────────────
      - uses: actions/checkout@v4

      # ── Multi-arch (QEMU) ─────────────────────────────────────────────
      - uses: docker/setup-qemu-action@v3

      # ── Buildx builder with entitlements enabled ─────────────────────
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          buildkitd-flags: |
            --allow-insecure-entitlement security.insecure
            --allow-insecure-entitlement network.host

      # ── Login to GHCR ─────────────────────────────────────────────────
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ── Build & push ─────────────────────────────────────────────────
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          push: true
          provenance: false

          # >>> THIS is the critical bit <<<
          allow: |
            security.insecure
            network.host

          build-args: |
            FLAVOR=${{ matrix.BASE_FLAVOR }}
            FEDORA_TAG=${{ matrix.FEDORA_TAG }}

          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.BASE_FLAVOR }}-${{ matrix.FEDORA_TAG }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

          cache-from: type=gha
          cache-to:   type=gha,mode=max