name: Build-and-Publish bootc images

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io            # target registry (GHCR)
  # No global FEDORA_VERSION now—version is set per flavour

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # Core image already published on Fedora 40
          - flavor: core
            fedora: 40
          # Bluefin 40 not public yet → pin to 39 for now
          - flavor: bluefin
            fedora: 39

    steps:
    # ───── checkout ───────────────────────────────────────────
    - name: Checkout source
      uses: actions/checkout@v4

    # ───── lower-case owner/repo for GHCR tags ───────────────
    - name: Normalise repo name
      run: |
        echo "IMAGE_REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

    # ───── buildx toolchain ──────────────────────────────────
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    # ───── login to GHCR ─────────────────────────────────────
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ───── build & push image ────────────────────────────────
    - name: Build and push ${{ matrix.flavor }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Containerfile
        build-args: |
          FLAVOR=${{ matrix.flavor }}
          FEDORA_VERSION=${{ matrix.fedora }}
        provenance: false
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ matrix.flavor }}-${{ github.sha }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_REPO }}
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}