name: Build-and-Publish bootc images

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}   # ghcr.io/<owner>/<repo>

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [core, bluefin]          # add more later if needed
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push ${{ matrix.flavor }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Containerfile
        build-args: |
          FLAVOR=${{ matrix.flavor }}
          FEDORA_VERSION=40
        provenance: false          # smaller layers
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.flavor }}-latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.flavor }}-${{ github.sha }}
        labels: |
          org.opencontainers.image.title=${{ env.IMAGE_NAME }}
          org.opencontainers.image.version=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ env.IMAGE_NAME }}