# .github/workflows/build-bootc.yml
name: Build bootc images
on:
  push: {branches: [main]}
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME:     huntergerlach/infra-upstream

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - BASE_FLAVOR: bluefin
            FEDORA_TAG:  stable

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3

      # ── builder with entitlements ──────────────────────────────────────
      - id: buildx                       # <- save the builder name
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
          buildkitd-flags: |
            --allow-insecure-entitlement security.insecure
            --allow-insecure-entitlement network.host

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ── build & push ───────────────────────────────────────────────────
      - uses: docker/build-push-action@v5
        with:
          # Explicitly use the builder we just created
          builder: ${{ steps.buildx.outputs.name }}

          context: .
          file: Containerfile
          push: true
          provenance: false

          # **one line per entitlement**
          allow: |
            security.insecure
            network.host

          build-args: |
            FLAVOR=${{ matrix.BASE_FLAVOR }}
            FEDORA_TAG=${{ matrix.FEDORA_TAG }}

          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.BASE_FLAVOR }}-${{ matrix.FEDORA_TAG }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

          cache-from: type=gha
          cache-to:   type=gha,mode=max