# .github/workflows/smoke-test.yml
name: smoke-test bootc image

###############################################################################
#  Trigger                                                                    #
#  ─────────────────────────────────────────────────────────────────────────── #
#  Runs automatically after *successful* completion of the build-bootc        #
#  workflow.  (The name here must match the `name:` in build-bootc.yml)       #
###############################################################################
on:
  workflow_run:
    workflows: [ build-bootc ]
    types: [ completed ]

###############################################################################
#  Smoke-test job                                                             #
###############################################################################
jobs:
  smoke-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04          # any runner with Docker/Podman works
    permissions:
      packages: read               # pull from GHCR
      contents: read

    env:
      REGISTRY: ghcr.io
      IMAGE:    huntergerlach/infra-upstream
      # commit-SHA tag that the build workflow always pushes
      SHA_TAG:  ${{ github.event.workflow_run.head_sha }}

    steps:
    # ────────────────────────────────────────────────────────────────────────
    # authenticate to GHCR
    # ────────────────────────────────────────────────────────────────────────
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ────────────────────────────────────────────────────────────────────────
    # pull the freshly-built image
    # ────────────────────────────────────────────────────────────────────────
    - name: Pull image (commit tag)
      run: |
        docker pull $REGISTRY/$IMAGE:$SHA_TAG

    # ────────────────────────────────────────────────────────────────────────
    # trivial “does it start?” check – htop must run
    # ────────────────────────────────────────────────────────────────────────
    - name: htop should print version
      run: |
        docker run --rm $REGISTRY/$IMAGE:$SHA_TAG htop --version

    # ────────────────────────────────────────────────────────────────────────
    # system summary for easy debugging (fastfetch)
    # ────────────────────────────────────────────────────────────────────────
    - name: Show fastfetch output
      run: |
        echo "::group::fastfetch"
        # fastfetch already dumps to stdout; --pipe gives a concise one-liner
        docker run --rm $REGISTRY/$IMAGE:$SHA_TAG fastfetch --logo none --pipe
        echo "::endgroup::"

    # ────────────────────────────────────────────────────────────────────────
    # verify the OCI metadata label we expect
    # ────────────────────────────────────────────────────────────────────────
    - name: Inspect OCI labels
      run: |
        skopeo inspect docker://$REGISTRY/$IMAGE:$SHA_TAG \
          | jq -r '.Labels["org.opencontainers.image.source"]' \
          | grep -q "https://github.com/HunterGerlach/infra-upstream"

    # ────────────────────────────────────────────────────────────────────────
    # confirm bootc CLI is present (quick sanity check)
    # ────────────────────────────────────────────────────────────────────────
    - name: Confirm bootc is on PATH
      run: |
        docker run --rm $REGISTRY/$IMAGE:$SHA_TAG which bootc