# .github/workflows/smoke-test.yml
name: smoke-test bootc image

on:
  workflow_run:
    workflows: [ build-bootc ]
    types: [ completed ]

jobs:
  smoke-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    permissions:
      packages: read
      contents: read

    env:
      REGISTRY: ghcr.io
      IMAGE: huntergerlach/infra-upstream
      SHA_TAG: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull $REGISTRY/$IMAGE:$SHA_TAG

      - name: Quick command check (htop)
        run: docker run --rm $REGISTRY/$IMAGE:$SHA_TAG htop --version

      - name: Show fastfetch output
        run: |
          echo "::group::fastfetch"
          docker run --rm $REGISTRY/$IMAGE:$SHA_TAG fastfetch --logo none --stdout
          echo "::endgroup::"

      - name: Inspect OCI labels
        run: |
          skopeo inspect docker://$REGISTRY/$IMAGE:$SHA_TAG | \
            jq '.Labels["org.opencontainers.image.source"]' | \
            grep -q "https://github.com/HunterGerlach/infra-upstream"

      - name: Confirm bootc is on PATH
        run: docker run --rm $REGISTRY/$IMAGE:$SHA_TAG which bootc