# .github/workflows/smoke-test.yml
name: smoke-test bootc image

# ── trigger ────────────────────────────────────────────────────────────────
# Fires as soon as the `build-bootc` workflow completes *successfully*
on:
  workflow_run:
    workflows: [ build-bootc ]      # must exactly match the name: in build file
    types:    [ completed ]

jobs:
  smoke-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04           # any runner with Docker/Podman works
    permissions:
      packages: read                # pull from GHCR
      contents: read

    env:
      REGISTRY: ghcr.io
      IMAGE:    huntergerlach/infra-upstream
      # use the HEAD commit SHA of the build run as our “unique” tag.
      # that tag is always pushed by build-bootc in addition to <flavour>-<tag>
      SHA_TAG: ${{ github.event.workflow_run.head_sha }}

    steps:
      # ── authenticate to GHCR ────────────────────────────────────────────
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ── pull the freshly-built image ────────────────────────────────────
      - name: Pull image (commit tag)
        run: |
          docker pull $REGISTRY/$IMAGE:$SHA_TAG

      # ── trivial “does it start?” check ──────────────────────────────────
      - name: Run command inside container
        run: |
          docker run --rm $REGISTRY/$IMAGE:$SHA_TAG htop --version

      # ── verify metadata labels are present ──────────────────────────────
      - name: Inspect OCI labels
        run: |
          skopeo inspect docker://$REGISTRY/$IMAGE:$SHA_TAG | \
            jq '.Labels["org.opencontainers.image.source"]' | \
            grep -q "https://github.com/HunterGerlach/infra-upstream"

      # ── (optional) quick bootc sanity check — confirm CLI is present ────
      - name: Confirm bootc is on PATH
        run: |
          docker run --rm $REGISTRY/$IMAGE:$SHA_TAG which bootc

      # ── (optional) add your own checks here … ───────────────────────────
      # e.g. cosign verify, trivy scan, minimal boot, etc.